Copygram/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts
  get 'posts/:id' => 'posts#show'
     
  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  get 'access/signup'
  post 'access/signupAttempt'
  post 'access/attempt'
  get 'access/logout'
    get 'help', :to => 'access#help'
    get 'access/help'
    
  get 'users/' => 'users#show'
    
  resources :posts do
   resources :likes
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
    
    
end

Copygram/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Copygram/app/models/like.rb
class Like < ApplicationRecord
end

Copygram/app/models/post.rb
class Post < ApplicationRecord
    # associates attribute :image with a file attachment
	has_attached_file :image, styles: { 
		small: "64x64", 
		med: "200x200", 
		large: "400x400" 
	}
 
	# Validate the attached image is image/jpg, image/png, etc
	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

Copygram/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

Copygram/app/controllers/access_controller.rb
class AccessController < ApplicationController
  def menu
      if session[:user_id] != nil
    @myAccount = User.find_by(id: session[:user_id])
    @user = session[:user_id]
    @posts = Post.where(:user_id => @myAccount.id)
    @likes = Like.all
      else
          redirect_to(root_path)
      end
  end

  def login
      if session['user_id'] != nil
          flash[:notice] = "Log out to sign in to another account."
          redirect_to(root_path)
      else
      end
      
  end
  
  def signup
      @user = session[:user_id]
      if @user == nil
          
      else
          flash[:notice] = "Log out to create a new account."
          redirect_to(root_path)
      end
  end 
    
  def signupAttempt
      @user = session[:user_id]
      if @user == nil
      if params[:name].present? && params[:password].present? && params[:email].present?
            searchUser = User.where(:name => params[:name]).first
            if searchUser
               authorizeUser = searchUser.authenticate(params[:password])
            end
        end
      
      if authorizeUser
            flash.now[:notice] = "User already exists."
            render('signup')
        else
            newUser = User.new
            newUser.name = params[:name]
            newUser.email = params[:email]
            newUser.password = params[:password]
            newUser.save
          
            session[:user_id] = newUser.id
            flash[:notice] = "Logged in successfully."
            redirect_to(admin_path)
        end
      else
          flash[:notice] = "Log out to create a new account."
          redirect_to(root_path)
      end
          
  end
    
    
    def attempt
        if params[:name].present? && params[:password].present?
            searchUser = User.where(:name => params[:name]).first
            if searchUser
               authorizeUser = searchUser.authenticate(params[:password])
            end
        end
        
        if authorizeUser
            session[:user_id] = authorizeUser.id
            flash[:notice] = "Logged in successfully."
            redirect_to(admin_path)
        else
            flash.now[:notice] = "Invalid username/password."
            render('login')
        end
    end
    
    def logout
        if session['user_id'] != nil
        session['user_id'] = nil
        flash[:notice] = 'Logged out.'
        else
           flash[:notice] = 'You are already not logged in.' 
        end    
        redirect_to(access_login_path)
    end
    
    def help
    end
    
end

Copygram/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    
    before_action :set_page


    def set_page
      if session[:user_id] == nil
          @userSes = "Hello, guest!"
      else
          @userSes = User.find_by(id: session[:user_id])
          @userSes = "Hello, " + @userSes.name + "!"
      end
    end
end

Copygram/app/controllers/likes_controller.rb
class LikesController < ApplicationController
    
    def index
    end
    
    def create
        if session['user_id'] != nil
        l = Like.new
        l.post_id = params["post_id"]
        p = Post.find_by(id: params["post_id"])
        l.user_id = p.user_id
        l.save
        redirect_to "/", notice: 'Successfully liked.'
        else
            flash[:notice] = "Log in to like."
          redirect_to(root_path)
        end
    end
    
    def destroy
        if session['user_id'] != nil
        l = Like.find_by(post_id: params["post_id"])
        l.destroy
        redirect_to "/", notice: 'Successfully unliked.'
        else
           flash[:notice] = "Log in to like."
          redirect_to(root_path) 
        end
    end
    
end

Copygram/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    
    def index
		@posts = Post.all
        @likes = Like.all
        @user = session[:user_id]
    end
	
 
 	def new
        @user = session[:user_id]
        if @user == nil
            flash[:notice] = "Log in to post."
          redirect_to(root_path)
        else    
 		@post = Post.new :user_id => session[:user_id]
        end
 	end
 
 	def create
        @user = session[:user_id]
        if @user != nil
 		@post = Post.new(post_params)
 		if @post.save
 			redirect_to posts_path
 		else
 			render :new
 		end
        else
          flash[:notice] = "Log in to post."
          redirect_to(root_path)
        end
 	end
    
    def show
        @p = Post.where(:id => params["id"])
        @likes = Like.all
        @user = session[:user_id] 
    end
    
    def edit
        @p = Post.where(:id => params["id"]).first
        if session[:user_id] == @p.user_id
        
        else
          flash[:notice] = "You do not have permission to edit this post."
          redirect_to(root_path)
        end
    end
    
    def update
    p = Post.find_by(id: params["id"])
        
    if session[:user_id] == p.user_id
    p.title = params["title"]
    p.description = params["description"]
    p.save
    redirect_to "/posts/#{p.id}", notice: 'Post successfully updated.'
    else
        redirect_to "/posts/#{p.id}", notice: 'You do not have permission to edit this post.'
    end
        
        
    end
    
    def destroy
        p = Post.find_by(id: params["id"])
        
        if session[:user_id] == p.user_id
        p.destroy
        redirect_to "/access/menu", notice: 'Successfully deleted your post.'
        else
            redirect_to "/posts/#{p.id}", notice: 'You do not have permission to edit this post.'
        end
    end
 
    private 
 	def post_params
 		params.require(:post).permit(:title, :description, :user_id, :image)
 	end
        
    
end

Copygram/app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
        @user = session[:user_id]
        if User.where(:name => params[:name]).count > 0
         @userAccount = User.find_by(name: params[:name])
         @posts = Post.where(:user_id => @userAccount.id)
         @likes = Like.all
        else
            flash[:notice] = 'User not found.'
            redirect_to root_path
        end
    end
    
    
end

Copygram/app/helpers/access_helper.rb
module AccessHelper
end

Copygram/app/helpers/application_helper.rb
module ApplicationHelper
end

Copygram/app/views/access/help.html.erb
<h1>User Stories</h1>

<p>As a visitor, I want to see other user's posts.</p>
<p>As a visitor, I want to click on a post to see more details.</p>
<p>As a visitor, I want to sign up for a free account.</p>
<p>As a user, I want to post with a title, image, description.</p>
<p>As a user, I want to edit my post.</p>
<p>As a user, I want to delete a post that I wrote.</p>
<p>As a user, I want to like/unlike posts.</p>

<h1>Business Rules</h1>

<p>Posts are stored in a database. Images are stored on AWS S3.</p>
<p>A post consists of an image, a title, and description.</p>
<p>Posting an item automatically adds it to your account page and the wall all users can see.</p>
<p>Passwords must be encrypted.</p>

Copygram/app/views/access/login.html.erb
<div class = "row">
    <div class = "col-md-4">
    </div>
<div class = "col-md-4 text-center">
    <% if !flash.empty? %>
            <div class="alert alert-info">
                <%= flash[:notice] %>
            </div>
        <% end %>
<h1>Login</h1>

<div class= "login">

<%= form_tag(access_attempt_path, :method => :post) do %>
    <table>
        <tr>
            <td><%= label_tag(:name) %></td>
            <td><%= text_field_tag(:name, params[:name], class: 'form-control') %></td>
        </tr>
        
        <tr>
            <td><%= label_tag(:password) %></td>
            <td><%= password_field_tag(:password, nil, class: 'form-control') %></td>
        </tr>
        
        <tr>
            <td><%= submit_tag("Log In", class: 'btn btn-default btn-md btn-submit')%></td>
        </tr>
    
    
    </table>
    
    <% end %>

</div>
    </div>
    <div class = "col-md-4">
    </div>
</div>

Copygram/app/views/access/menu.html.erb
<div class = "row">
    <div class = "col-md-4">
    </div>
<div class = "col-md-4 text-center">
    <% if !flash.empty? %>
            <div class="alert alert-info">
                <%= flash[:notice] %>
            </div>
        <% end %>
    <h2>Your Posts</h2>
    
    <% @posts.each do |post| %>
    <div style="border: thin solid gray">
    <p><strong><%= User.find(post.user_id).name %></strong></p>
        
    <%= image_tag post.image.url(:large) %>
    <br>
    <% if @likes.where(:user_id => @user, :post_id => post.id).count > 0 %>
        <%= link_to 'Unlike', '/posts/%{postId}/likes/1' % {:postId => post.id}, :class => "btn", method: :delete, class: 'btn btn-default navbar-btn' %>
    <% else %>   
        <%= link_to 'Like', '/posts/%{postId}/likes' % {:postId => post.id}, :class => "btn", method: :post, class: 'btn btn-default navbar-btn' %>
    <% end %>
        
    <p><strong><%= @likes.where(post_id: post.id).count %> likes</strong></p>
    <p><strong><%= post.title %></strong></p>
    <p><%= post.description %></p>
    <%= link_to 'More...', '/posts/%{postId}' % {:postId => post.id}, :class => "btn", method: :get, class: 'btn btn-default navbar-btn' %>
    </div>
<% end %>

    </div>
    <div class = "col-md-4">
    </div>
</div>

Copygram/app/views/access/signup.html.erb
<h1>Signup</h1>

<div class= "signup">

<%= form_tag(access_signupAttempt_path, :method => :post) do %>
    <table>
        <tr>
            <td><%= label_tag(:name) %></td>
            <td><%= text_field_tag(:name, params[:name]) %></td>
        </tr>
        
        <tr>
            <td><%= label_tag(:email) %></td>
            <td><%= text_field_tag(:email, params[:email]) %></td>
        </tr>
        
        <tr>
            <td><%= label_tag(:password) %></td>
            <td><%= password_field_tag(:password) %></td>
        </tr>
        
        <tr>
            <td><%= submit_tag("Sign Up")%></td>
        </tr>
    
    
    </table>
    
    <% end %>

</div>

Copygram/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Change This Title</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
      
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      
  </head>

  <body style="padding-top: 70px;">
    <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Copygram", "/", class: "navbar-brand" %>
    </div>
      
    <ul class="nav navbar-nav">
      <% if @userSes == "Hello, guest!"%>
        <li><a><%=@userSes%></a></li>
      <% else %>    
      <li><%= link_to @userSes, "/access/menu" %></li>
      <% end %>
      <li><%= link_to "Sign Up", "/access/signup" %></li>
      <li><%= link_to "Sign In", '/access/login' %></li>
      <li><%= link_to "Sign Out", '/access/logout'%></li>
    </ul>
      
    <div class="navbar-form navbar-left">
    <%= form_tag('/users/', :method => "get", id: "search-form") do %>
    <%= text_field_tag :name, params[:name], placeholder: "Search for user...", class: "form-control" %>
    <%= submit_tag "Search", :name => nil, class: 'btn btn-default btn-md btn-submit' %>
     <% end %>
      </div>
      
      
    <div class="navbar-right">
        
        <%= link_to "Post", new_post_path, class: 'btn btn-default navbar-btn' %>
            
    </div>
      
       
  </div>
</nav>
      
    <%= yield %>
        
  </body>
</html>

Copygram/app/views/posts/edit.html.erb
<div class="row">
    <div class="col-sm-4">
    </div>
  <div class="col-sm-4">

  <%= form_tag("/posts/#{@p.id}", method: 'patch') do  %>

    <div class="form-group">
      <%= label_tag :title, "Title" %>
      <%= text_field_tag :title, @p.title, autofocus: true, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= label_tag :description, "Description" %>
      <%= text_area_tag :description, @p.description,
                        rows: 5, class: 'form-control' %>
    </div>

    <%= submit_tag "Update", class: 'btn btn-success btn-lg'%>
    or
    <%= link_to "Cancel", "/" %>

  <% end %>

  </div>
    <div class="col-sm-4">
    </div>
</div>

Copygram/app/views/posts/index.html.erb
<div class = "row">
    <div class = "col-md-4">
    </div>
    <div class = "col-md-4 text-center">
        <% if !flash.empty? %>
            <div class="alert alert-info">
                <%= flash[:notice] %>
            </div>
        <% end %>
<% @posts.each do |post| %>
    <div style="border: thin solid gray">
    <p><strong><%= User.find(post.user_id).name %></strong></p>
        
    <%= image_tag post.image.url(:large) %>
    <br>
    <% if @likes.where(:user_id => @user, :post_id => post.id).count > 0 %>
        <%= link_to 'Unlike', '/posts/%{postId}/likes/1' % {:postId => post.id}, :class => "btn", method: :delete, class: 'btn btn-default navbar-btn' %>
    <% else %>   
        <%= link_to 'Like', '/posts/%{postId}/likes' % {:postId => post.id}, :class => "btn", method: :post, class: 'btn btn-default navbar-btn' %>
    <% end %>
        
    <p><strong><%= @likes.where(post_id: post.id).count %> likes</strong></p>
    <p><strong><%= post.title %></strong></p>
    <p><%= post.description %></p>
    <%= link_to 'More...', '/posts/%{postId}' % {:postId => post.id}, :class => "btn", method: :get, class: 'btn btn-default navbar-btn' %>
    </div>
<% end %>
    </div>
    <div class = "col-md-4">
    </div>
</div>


 

Copygram/app/views/posts/new.html.erb
<%= form_for @post do |f| %>
	<p>
    	<%= f.label :title %>
    	<%= f.text_field :title %>
        
        <%= f.label :description %>
    	<%= f.text_field :description %>
        
    	<%= f.hidden_field :user_id %>
  	</p>
  	<p>
    	<%= f.file_field :image %>
  	</p>
 
  	<%= f.submit %>
<% end %>

Copygram/app/views/posts/show.html.erb
<div class = "row">
    <div class = "col-md-4">
    </div>
    <div class = "col-md-4 text-center">
        <% if !flash.empty? %>
            <div class="alert alert-info">
                <%= flash[:notice] %>
            </div>
        <% end %>
<% @p.each do |post| %>
    <div style="border: thin solid gray">
    <p><strong><%= User.find(post.user_id).name %></strong></p>
        
    <%= image_tag post.image.url(:large) %>
    <br>
    <% if @likes.where(:user_id => @user, :post_id => post.id).count > 0 %>
        <%= link_to 'Unlike', '/posts/%{postId}/likes/1' % {:postId => post.id}, :class => "btn", method: :delete, class: 'btn btn-default navbar-btn' %>
    <% else %>   
        <%= link_to 'Like', '/posts/%{postId}/likes' % {:postId => post.id}, :class => "btn", method: :post, class: 'btn btn-default navbar-btn' %>
    <% end %>
        
    <p><strong><%= @likes.where(post_id: post.id).count %> likes</strong></p>
    <p><strong><%= post.title %></strong></p>
    <p><%= post.description %></p>
    <%= link_to 'Edit', '/posts/%{postId}/edit' % {:postId => post.id}, :class => "btn", method: :get, class: 'btn btn-default navbar-btn' %>
    <%= link_to 'Delete', '/posts/%{postId}' % {:postId => post.id}, :class => "btn", method: :delete, class: 'btn btn-default navbar-btn' %>
    </div>
<% end %>
    </div>
    <div class = "col-md-4">
    </div>
</div>

Copygram/app/views/users/show.html.erb
<div class = "row">
    <div class = "col-md-4">
    </div>
    <div class = "col-md-4 text-center">
    <h1><%= @userAccount.name %>'s Posts</h1>
<% @posts.each do |post| %>
    <div style="border: thin solid gray">
    <p><strong><%= User.find(post.user_id).name %></strong></p>
        
    <%= image_tag post.image.url(:large) %>
    <br>
    <% if @likes.where(:user_id => @user, :post_id => post.id).count > 0 %>
        <%= link_to 'Unlike', '/posts/%{postId}/likes/1' % {:postId => post.id}, :class => "btn", method: :delete, class: 'btn btn-default navbar-btn' %>
    <% else %>   
        <%= link_to 'Like', '/posts/%{postId}/likes' % {:postId => post.id}, :class => "btn", method: :post, class: 'btn btn-default navbar-btn' %>
    <% end %>
        
    <p><strong><%= @likes.where(post_id: post.id).count %> likes</strong></p>
    <p><strong><%= post.title %></strong></p>
    <p><%= post.description %></p>
    <%= link_to 'More...', '/posts/%{postId}' % {:postId => post.id}, :class => "btn", method: :get, class: 'btn btn-default navbar-btn' %>
    </div>
<% end %>
    </div>
    <div class = "col-md-4">
    </div>
</div>